#kafka:
#  consumer:
#    topic: Desarrollo--realestate--contacto
#    group: socratest
#    client: clientTest
#    brokers: rxkaf-stg-kafk-brok-1.stg.rxkaf.re.navent.biz:9092,rxkaf-stg-kafk-brok-2.stg.rxkaf.re.navent.biz:9092,rxkaf-stg-kafk-brok-3.stg.rxkaf.re.navent.biz:9092
    

#elasticsearch:
#  hosts: localhost:9300
#  cluster-name: cluster_test
#  index-name: socratest

 